"""
Ontology definitions: class mappings, predicate mappings, and normalization helpers.
"""

NER_LABEL_TO_CLASS = {
    "PERSON": "Person",
    "WORK_OF_ART": "Film",
    "ORG": "Organization",
    "GPE": "Location",
    "LOC": "Location",
    "FAC": "Location",
    "DATE": "Date",
}

CLASSES = ["Person", "Film", "Organization", "Location", "Date"]

PREDICATES = [
    "DIRECTED",
    "PRODUCED",
    "COMPOSED",
    "WROTE",
    "FOUNDED",
    "RELEASED_IN",
    "WORKED_ON",
    "RELATED_TO",
]

LEMMA_TO_PREDICATE = {
    "direct": "DIRECTED",
    "compose": "COMPOSED",
    "score": "COMPOSED",
    "conduct": "COMPOSED",
    "produce": "PRODUCED",
    "write": "WROTE",
    "author": "WROTE",
    "found": "FOUNDED",
    "establish": "FOUNDED",
    "co-found": "FOUNDED",
    "cofound": "FOUNDED",
    "release": "RELEASED_IN",
    "premiere": "RELEASED_IN",
    "screen": "RELEASED_IN",
    "create": "WORKED_ON",
    "work": "WORKED_ON",
    "animate": "WORKED_ON",
    "design": "WORKED_ON",
    "draw": "WORKED_ON",
    "publish": "WORKED_ON",
    "develop": "WORKED_ON",
    "adapt": "WORKED_ON",
    "make": "WORKED_ON",
    "collaborate": "WORKED_ON",
    "perform": "WORKED_ON",
    "appear": "WORKED_ON",
    "star": "WORKED_ON",
    "voice": "WORKED_ON",
    "play": "WORKED_ON",
    "base": "WORKED_ON",
    "inspire": "WORKED_ON",
    "influence": "WORKED_ON",
    "feature": "WORKED_ON",
    "name": "WORKED_ON",
    "become": "RELATED_TO",
    "include": "RELATED_TO",
    "have": "RELATED_TO",
    "be": "RELATED_TO",
    "say": "RELATED_TO",
    "tell": "RELATED_TO",
    "use": "RELATED_TO",
    "receive": "RELATED_TO",
    "win": "RELATED_TO",
    "earn": "RELATED_TO",
    "open": "RELATED_TO",
    "set": "RELATED_TO",
    "take": "RELATED_TO",
    "serve": "RELATED_TO",
    "leave": "RELATED_TO",
    "join": "RELATED_TO",
    "move": "RELATED_TO",
    "return": "RELATED_TO",
    "start": "RELATED_TO",
    "continue": "RELATED_TO",
    "begin": "RELATED_TO",
    "lead": "RELATED_TO",
    "follow": "RELATED_TO",
    "come": "RELATED_TO",
    "go": "RELATED_TO",
}

PREDICATE_ANCHORS = {
    "DIRECTED": "directed",
    "PRODUCED": "produced",
    "COMPOSED": "composed",
    "WROTE": "wrote",
    "FOUNDED": "founded",
    "RELEASED_IN": "released",
    "WORKED_ON": "worked",
}
